# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef858b89d5f0d202ba496ba71833f3ee3e4d89e0cd12614ef6d5765de0dd96ae5d69c9a1a8738d7b5a9149f6823b8a8741ddc5b846f59f40d14c220821e58726

test:
  secret_key_base: 49d77e9d18e4cfa53bd1ba67c6fe66688b31f454cdd52b7ce225f3632475f16643e8b76152b0ce17fcd1aa95a153363c00bd6010e82a9d16a12922d26f1e0340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
